# Generated by Django 5.2.4 on 2026-04-03 16:43

import bonding.models.user
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonding', '0002_notification_verificationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=8)),
                ('likes_per_day', models.PositiveIntegerField(default=100)),
                ('can_see_who_liked', models.BooleanField(default=False)),
                ('has_unlimited_swipes', models.BooleanField(default=False)),
                ('has_priority_boost', models.BooleanField(default=False)),
                ('has_video_calls', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['price_monthly'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', bonding.models.user.BondingUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='connection',
            name='is_mutual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='location',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='allow_video_calls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_distance_km',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_preferred_age',
            field=models.PositiveIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='profile',
            name='min_preferred_age',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='premium_tier',
            field=models.CharField(choices=[('free', 'Free'), ('plus', 'Plus'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_age',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='connection',
            name='status',
            field=models.CharField(choices=[('like', 'Like'), ('pass', 'Pass'), ('superlike', 'Super Like')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_MESSAGE', 'Nova Mensagem'), ('NEW_CONNECTION', 'Nova Conexao'), ('NEW_MATCH', 'Novo Match'), ('LIKE_RECEIVED', 'Voce recebeu um Like'), ('PROFILE_VERIFIED', 'Perfil verificado'), ('VIDEO_CALL_INVITE', 'Convite para videochamada'), ('PREMIUM_UPDATED', 'Plano premium atualizado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Masculino'), ('female', 'Feminino'), ('non_binary', 'Nao-binario'), ('fluid', 'Genero fluido'), ('other', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sexual_orientation',
            field=models.CharField(choices=[('straight', 'Heterossexual'), ('gay', 'Homossexual'), ('bisexual', 'Bissexual'), ('asexual', 'Assexual'), ('pansexual', 'Pansexual'), ('other', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('provider', models.CharField(choices=[('fcm', 'Firebase'), ('expo', 'Expo'), ('web_push', 'Web Push')], default='fcm', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('fake', 'Perfil falso'), ('abuse', 'Abuso'), ('inappropriate', 'Conteudo inapropriado'), ('other', 'Outro')], max_length=30)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('reviewing', 'Em revisao'), ('resolved', 'Resolvido'), ('dismissed', 'Descartado')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('active', 'Ativa'), ('canceled', 'Cancelada'), ('expired', 'Expirada')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='bonding.premiumplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoCallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=120, unique=True)),
                ('provider', models.CharField(default='webrtc', max_length=40)),
                ('status', models.CharField(choices=[('requested', 'Solicitada'), ('accepted', 'Aceita'), ('declined', 'Recusada'), ('finished', 'Finalizada')], default='requested', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_calls', to='bonding.conversation')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_calls_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='bonding.conversation')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user1', 'user2')},
            },
        ),
    ]
