# Generated by Django 5.2.4 on 2026-04-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonding', '0005_institution_message_consumed_at_message_is_view_once_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='spotify_album_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='spotify_artist_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='spotify_preview_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='spotify_track_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='spotify_track_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='spotify_track_url',
            field=models.URLField(blank=True),
        ),
    ]
