# Generated by Django 5.2.4 on 2026-04-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonding', '0008_profile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='client_request_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='client_request_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='client_request_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('sender', 'client_request_id'), name='bonding_message_sender_client_request_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('profile', 'client_request_id'), name='bonding_photo_profile_client_request_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='story',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id__isnull', False)), fields=('author', 'client_request_id'), name='bonding_story_author_client_request_id_uniq'),
        ),
    ]
