# Generated by Django 5.2.4 on 2026-04-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonding', '0011_seed_premium_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='provider_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('video', 'Video'), ('story_reply', 'Resposta de story'), ('date_suggestion', 'Sugestão de date')], default='text', max_length=20),
        ),
    ]
