# Generated by Django 5.2.4 on 2026-05-09 01:22

import bonding.security_crypto
from django.db import migrations, models


def encrypt_provider_payloads(apps, schema_editor):
    Message = apps.get_model("bonding", "Message")
    ProfileVerificationAttempt = apps.get_model("bonding", "ProfileVerificationAttempt")

    for message in Message.objects.exclude(provider_payload__isnull=True).iterator(chunk_size=200):
        Message.objects.filter(pk=message.pk).update(
            provider_payload_encrypted=bonding.security_crypto.encrypt_object(message.provider_payload)
        )

    for attempt in ProfileVerificationAttempt.objects.iterator(chunk_size=200):
        payload = attempt.provider_payload if attempt.provider_payload is not None else {}
        ProfileVerificationAttempt.objects.filter(pk=attempt.pk).update(
            provider_payload_encrypted=bonding.security_crypto.encrypt_object(payload)
        )


class Migration(migrations.Migration):

    dependencies = [
        ("bonding", "0013_merge_premium_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="provider_payload_encrypted",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profileverificationattempt",
            name="provider_payload_encrypted",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.RunPython(encrypt_provider_payloads, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="message",
            name="provider_payload",
        ),
        migrations.RemoveField(
            model_name="profileverificationattempt",
            name="provider_payload",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="provider_payload_encrypted",
            new_name="provider_payload",
        ),
        migrations.RenameField(
            model_name="profileverificationattempt",
            old_name="provider_payload_encrypted",
            new_name="provider_payload",
        ),
        migrations.AlterField(
            model_name="message",
            name="provider_payload",
            field=bonding.security_crypto.EncryptedJSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profileverificationattempt",
            name="provider_payload",
            field=bonding.security_crypto.EncryptedJSONField(blank=True, default=dict),
        ),
    ]
