# Generated by Django 5.2.4 on 2026-08-11 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonding', '0016_remove_profile_allow_study_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationStageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('quebra_gelo', 'Quebra-gelo'), ('rapport', 'Rapport'), ('interesse_mutuo', 'Interesse mútuo'), ('pronto_para_role', 'Pronto para rolê')], default='quebra_gelo', max_length=32)),
                ('stage_confidence', models.PositiveSmallIntegerField(default=0)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('tipo_role', models.CharField(blank=True, max_length=32, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stage_snapshot', to='bonding.conversation')),
            ],
        ),
    ]
