# Generated by Django 5.2.4 on 2026-08-11 16:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonding', '0017_conversationstagesnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('terms_of_use', 'Termos de Uso'), ('privacy_policy', 'Politica de Privacidade')], max_length=32)),
                ('version_label', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('content_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('is_current', models.BooleanField(default=False)),
                ('effective_date', models.DateField()),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dpo_contact_snapshot', models.CharField(blank=True, help_text='Contato do Encarregado (DPO) vigente na publicacao desta versao. TODO: preencher quando houver Encarregado formalmente definido.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['document_type', '-published_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('document_type',), name='unique_current_legal_document_per_type')],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('general_terms', 'Termos de Uso'), ('privacy_policy', 'Politica de Privacidade'), ('biometric_verification', 'Verificacao biometrica facial'), ('precise_geolocation', 'Geolocalizacao precisa'), ('sensitive_profile_data', 'Dado sensivel de perfil (genero/orientacao sexual)')], max_length=32)),
                ('action', models.CharField(choices=[('granted', 'Concedido'), ('revoked', 'Revogado')], default='granted', max_length=10)),
                ('granted_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('prev_hash', models.CharField(max_length=64)),
                ('content_hash', models.CharField(max_length=64)),
                ('hmac_signature', models.CharField(max_length=64, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
                ('document_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consent_records', to='bonding.legaldocumentversion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
