# Generated by Django 5.2.4 on 2026-08-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonding', '0021_consent_account_lifecycle_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentrecord',
            name='consent_type',
            field=models.CharField(choices=[('general_terms', 'Termos de Uso'), ('privacy_policy', 'Politica de Privacidade'), ('biometric_verification', 'Verificacao biometrica facial'), ('precise_geolocation', 'Geolocalizacao precisa'), ('sensitive_profile_data', 'Dado sensivel de perfil (genero/orientacao sexual)'), ('account_deactivation', 'Desativacao de conta solicitada pelo usuario'), ('account_deletion', 'Exclusao de conta solicitada pelo usuario'), ('account_reactivation', 'Reativacao de conta via novo login')], max_length=32),
        ),
    ]
