# Generated by Django 5.2.4 on 2026-08-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonding', '0022_consent_account_reactivation_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentrecord',
            name='consent_type',
            field=models.CharField(choices=[('general_terms', 'Termos de Uso'), ('privacy_policy', 'Politica de Privacidade'), ('biometric_verification', 'Verificacao biometrica facial'), ('precise_geolocation', 'Geolocalizacao precisa'), ('sensitive_profile_data', 'Dado sensivel de perfil (genero/orientacao sexual)'), ('account_deactivation', 'Desativacao de conta solicitada pelo usuario'), ('account_deletion', 'Exclusao de conta solicitada pelo usuario'), ('account_reactivation', 'Reativacao de conta via novo login'), ('research_consent', 'TCLE - participacao na pesquisa academica')], max_length=32),
        ),
        migrations.AlterField(
            model_name='legaldocumentversion',
            name='document_type',
            field=models.CharField(choices=[('terms_of_use', 'Termos de Uso'), ('privacy_policy', 'Politica de Privacidade'), ('research_consent', 'Termo de Consentimento Livre e Esclarecido (TCLE)')], max_length=32),
        ),
    ]
