# Generated by Django 5.2.4 on 2026-08-12 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonding', '0024_publish_tcle_and_demo_mode_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationstagesnapshot',
            name='cached_suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='conversationstagesnapshot',
            name='last_suggested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversationstagesnapshot',
            name='last_suggested_message_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DateSuggestionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('shown', 'Shown')], default='shown', max_length=10)),
                ('place_name', models.CharField(max_length=255)),
                ('place_latitude', models.FloatField()),
                ('place_longitude', models.FloatField()),
                ('deterministic_score', models.FloatField(blank=True, null=True)),
                ('llm_score', models.FloatField(blank=True, null=True)),
                ('llm_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('metadata_completeness_score', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=20)),
                ('round_id', models.CharField(db_index=True, max_length=36)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_suggestion_feedback', to='bonding.conversation')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_suggestion_feedback', to='bonding.match')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conversation', '-created_at'], name='bonding_dat_convers_0ebaaa_idx')],
            },
        ),
    ]
