"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
from datetime import timedelta
from corsheaders.defaults import default_headers
import os
import dj_database_url


def env_bool(name, default=False):
    value = config(name, default=default)
    if isinstance(value, bool):
        return value
    if value is None:
        return default
    value = str(value).strip().lower()
    if value in {"1", "true", "yes", "on"}:
        return True
    if value in {"0", "false", "no", "off", ""}:
        return False
    if value == "release":
        return False
    return default


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', default=False)
SECURITY_HARDENING = env_bool("SECURITY_HARDENING", default=not DEBUG)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())

extra_allowed_hosts = config("ALLOWED_HOSTS_EXTRA", default="", cast=Csv())
for host in extra_allowed_hosts:
    cleaned_host = host.strip()
    if cleaned_host and cleaned_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(cleaned_host)

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "https://fatally-nether-lynnette.ngrok-free.dev",
]

configured_cors_origins = config("CORS_ALLOWED_ORIGINS", default="", cast=Csv())
for origin in configured_cors_origins:
    cleaned_origin = origin.strip().rstrip("/")
    if cleaned_origin and cleaned_origin not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(cleaned_origin)

extra_cors_origins = config("CORS_ALLOWED_ORIGINS_EXTRA", default="", cast=Csv())
for origin in extra_cors_origins:
    cleaned_origin = origin.strip().rstrip("/")
    if cleaned_origin and cleaned_origin not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(cleaned_origin)

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://[a-z0-9-]+\.ngrok-free\.dev$",
    r"^https://[a-z0-9-]+\.ngrok\.io$",
]
CORS_ALLOW_CREDENTIALS = env_bool("CORS_ALLOW_CREDENTIALS", default=True)
CORS_ALLOW_HEADERS = (*default_headers, "ngrok-skip-browser-warning")
DEFAULT_CORS_ALLOW_ALL = DEBUG and not SECURITY_HARDENING
# DEFAULT_CORS_ALLOW_ALL = False #Para testes com burpsuite. Nunca deixe isso como True em produção, mesmo que DEBUG seja True, por questões de segurança.
CORS_ALLOW_ALL_ORIGINS = env_bool("CORS_ALLOW_ALL_ORIGINS", default=DEFAULT_CORS_ALLOW_ALL)
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', cast=Csv(), default='')

# for origin in CORS_ALLOWED_ORIGINS:
#     parsed_origin = urlparse(origin)
#     if parsed_origin.hostname and parsed_origin.hostname not in ALLOWED_HOSTS:
#         ALLOWED_HOSTS.append(parsed_origin.hostname)
# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'bonding',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_yasg',
    'channels',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "UPDATE_LAST_LOGIN": True,
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'setup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'setup.wsgi.application'
ASGI_APPLICATION = 'setup.asgi.application'
AUTH_USER_MODEL = 'bonding.User'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"{config('DATABASE_URL')}",
        conn_max_age=0,
        conn_health_checks=True,
    )
}
default_engine = DATABASES["default"].get("ENGINE", "")
if "postgresql" in default_engine:
    DATABASES["default"].setdefault("OPTIONS", {})
    
    if SECURITY_HARDENING:
        # Modo de segurança máxima para Produção/Staging
        DATABASES["default"]["OPTIONS"].update({
            "sslmode": "verify-full", # Verifica a criptografia E a identidade do servidor
            "sslrootcert": os.path.join(BASE_DIR, ".certs", "prod-ca-2021.crt"),
        })
    else:
        # Modo relaxado para desenvolvimento local (se você rodar o Postgres num Docker local, por exemplo)
        DATABASES["default"]["OPTIONS"].setdefault(
            "sslmode", config("DATABASE_SSL_MODE", default="prefer")
        )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Fortaleza'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'static'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_ROOT = os.path.join(BASE_DIR,'media')
MEDIA_URL = '/media/'

# Email Configuration
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='localhost')
EMAIL_PORT = config('EMAIL_PORT', cast=int, default=25)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@bonding.local')
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', default=False)

SUPABASE_URL = config('SUPABASE_URL', default='')
SUPABASE_ANON_KEY = config('SUPABASE_ANON_KEY', default='')
SUPABASE_SERVICE_ROLE_KEY = config('SUPABASE_SERVICE_ROLE_KEY', default='')
SUPABASE_STORAGE_BUCKET = config('SUPABASE_STORAGE_BUCKET', default='profile-gallery')
SUPABASE_SIGNED_URL_TTL = config("SUPABASE_SIGNED_URL_TTL", cast=int, default=900)
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:8080')
BACKEND_URL = config('BACKEND_URL', default='http://127.0.0.1:8000')
ABACATEPAY_API_KEY = config('ABACATEPAY_API_KEY', default='')
ABACATEPAY_WEBHOOK_TOKEN = config('ABACATEPAY_WEBHOOK_TOKEN', default='')

# Modo demonstracao academica: ativa planos premium imediatamente, sem
# nenhuma chamada real ao AbacatePay e sem cobranca financeira. Usado no
# piloto de TCC com participantes reais (ver bonding/services/subscriptions.py).
PAYMENTS_DEMO_MODE = env_bool('PAYMENTS_DEMO_MODE', default=False)
GOOGLE_MAPS_API_KEY = config('GOOGLE_MAPS_API_KEY', default='')
AWS_REKOGNITION_ENABLED = env_bool('AWS_REKOGNITION_ENABLED', default=False)
VERIFICATION_PROVIDER = config('VERIFICATION_PROVIDER', default='aws_rekognition')
SPOTIFY_CLIENT_ID = config('SPOTIFY_CLIENT_ID', default='')
SPOTIFY_CLIENT_SECRET = config('SPOTIFY_CLIENT_SECRET', default='')
REDIS_URL = config('REDIS_URL', default='redis://127.0.0.1:6379/1')
REDIS_CELERY_URL = config('REDIS_CELERY_URL', default='redis://127.0.0.1:6379/2')
GOOGLE_SSV_ENABLED = config('GOOGLE_SSV_ENABLED', default=True, cast=bool)
GEMINI_API_KEY = config('GEMINI_API_KEY', default='')
DATE_SUGGESTION_CONFIDENCE_THRESHOLD = config("DATE_SUGGESTION_CONFIDENCE_THRESHOLD", cast=int, default=80)
DATE_SUGGESTION_COOLDOWN_MESSAGES = config("DATE_SUGGESTION_COOLDOWN_MESSAGES", cast=int, default=10)
DATE_SUGGESTION_COOLDOWN_HOURS = config("DATE_SUGGESTION_COOLDOWN_HOURS", cast=int, default=1)
DATE_SUGGESTION_DEDUP_DAYS = config("DATE_SUGGESTION_DEDUP_DAYS", cast=int, default=14)
FIELD_ENCRYPTION_KEY = config("FIELD_ENCRYPTION_KEY", default="")

AUTH_ACCESS_COOKIE_NAME = config("AUTH_ACCESS_COOKIE_NAME", default="bonding_access")
AUTH_REFRESH_COOKIE_NAME = config("AUTH_REFRESH_COOKIE_NAME", default="bonding_refresh")
AUTH_REFRESH_COOKIE_PATH = config("AUTH_REFRESH_COOKIE_PATH", default="/api/token/refresh/")
AUTH_COOKIE_SECURE = env_bool("AUTH_COOKIE_SECURE", default=SECURITY_HARDENING)
AUTH_COOKIE_SAMESITE = config("AUTH_COOKIE_SAMESITE", default="Lax")
AUTH_COOKIE_DOMAIN = config("AUTH_COOKIE_DOMAIN", default="")
AUTH_ACCESS_COOKIE_MAX_AGE = int(SIMPLE_JWT["ACCESS_TOKEN_LIFETIME"].total_seconds())
AUTH_REFRESH_COOKIE_MAX_AGE = int(SIMPLE_JWT["REFRESH_TOKEN_LIFETIME"].total_seconds())

SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", default=SECURITY_HARDENING)
SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", default=SECURITY_HARDENING)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", default=SECURITY_HARDENING)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = env_bool("CSRF_COOKIE_HTTPONLY", default=False)
SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", cast=int, default=31536000 if SECURITY_HARDENING else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=SECURITY_HARDENING)
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", default=SECURITY_HARDENING)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https") if SECURITY_HARDENING else None
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = config("SECURE_REFERRER_POLICY", default="same-origin")
X_FRAME_OPTIONS = config("X_FRAME_OPTIONS", default="DENY")

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
        "KEY_PREFIX": "bonding",
        "TIMEOUT": 300,
    }
}

CELERY_BROKER_URL = REDIS_CELERY_URL
CELERY_RESULT_BACKEND = REDIS_CELERY_URL
CELERY_TASK_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_IGNORE_RESULT = True

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
